#1 Common install by OS
- name: Because oracle linux install pip,python slowly,sleep 300s. drink water,please
  shell: echo "rest time"
  when: ansible_distribution == "OracleLinux"
  
- name: Sleep OK
  shell: sleep 300s
  when: ansible_distribution == "OracleLinux"
    
- debug:
    msg: Will install components on {{ ansible_distribution }}
  
- name: Check OS support, if not support, exit ansible
  fail: msg="OS not supported,exit!"
  when: ansible_distribution not in common_os_support

- include: "{{ansible_os_family}}.yml"


#2 Pip install
- block:
  - name: pip upgrade
    shell: python{{ansible_python.version.major}} -m pip install -U pip
    
  - name: Install pip requirements module
    pip:
      name: [pexpect,PyMySQL]
      extra_args: "-U" 
  when: common_install_python_modules
  
#3 Configure
- name: Create common folder
  file:
    path: '/data/{{item}}'
    state: directory
    recurse: yes
    mode: '0755'
  with_items:
    - logs
    - config
    - cert
    - wwwroot
    - apps

#4 Tool install
- name: Install tools
  include_tasks: tools_{{item}}.yml
  with_items: "{{common_install_tools}}"
  when: common_install_tools is defined and common_install_tools is not none and common_install_tools != "" and common_install_tools[0]!= ""
  
- block:
  - name: Set swapiness
    sysctl:
      name: vm.swappiness
      value: "10"

  - name: Fix No space left on device
    sysctl:
      name: fs.inotify.max_user_watches
      value: "8192000"
  when: ansible_distribution != 'OracleLinux'

- block:
  - name: set a regular hostname, remove "."
    shell: get_hostname=$(hostname);echo ${get_hostname%%.*}
    register: common_get_hostname
  - hostname:
      name: "{{common_get_hostname.stdout}}"
